use_frameworks!
platform :ios, '8.0'

target 'WBListKit_Example' do
  pod 'WBListKit', :path => '../'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'DZNEmptyDataSet'
  target 'WBListKit_Tests' do
    inherit! :search_paths

    
  end
end
