use_frameworks!

target 'WBListKit_Example' do
  pod 'WBListKit', :path => '../'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'HYNetworking'
  target 'WBListKit_Tests' do
    inherit! :search_paths

    
  end
end
